### ISSUE TITLE
Bugfix: lk_max_locks default to 537000

### ISSUE THREAD

**Issue by Rumhocker** [wattson-coder/SelaCoin#2]
Do you know what you do there? 
https://github.com/wattson-coder/SelaCoin/commit/c938f0fdcac4d8d7cd280f199da3b7e567500de1
Why do you have increase the max_locks? This has nothing to do with "safely handle reorgs with up to 5 blocks reversed"
Check the Oracle docs:
https://docs.oracle.com/cd/E17276_01/html/api_reference/C/envset_lk_max_locks.html

**Comment by watsoncoders** [comment]
yep reverted to defualt - the commit was approved as resut of an error, thank you
